config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/advertising.rb
class Advertising < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, :polymorphic => true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :images, :as => :imageable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images, :as => :imageable
end

app/controllers/advertisings_controller.rb
class AdvertisingsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :email, :password, :bio, :job, :relationship_status, :location ,:photo_id])
       devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :email, :password, :current_password, :bio, :job, :relationship_status, :location ,:photo_id])
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @posts = Post.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
      @images = Image.all
      render :json => @images
  end

  def new
     @image = current_user.image.build
  end

  def create
    @image = current_user.images.build(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    @image = Image.find(params[:id])

    respond_to do |format|
        if @image.update(image_params)
          format.html { redirect_to @image, notice: 'Image was successfully updated.' }
          format.json { render :show, status: :ok, location: @image }
        else
          format.html { render :edit }
          format.json { render json: @image.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @image.destroy
     respond_to do |format|
       format.html { redirect_to posts_url, notice: 'Image was successfully destroyed.' }
       format.json { head :no_content }
     end
  end

  def show
    @images = Image.all
  end


  private

  def post_params
     params.require(:image).permit(:user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
      @posts = Post.all
      render :json => @posts
  end

  def new
     @post = current_user.post.build
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @post.destroy
     respond_to do |format|
       format.html { redirect_to posts_url, notice: 'post was successfully destroyed.' }
       format.json { head :no_content }
     end
  end

  def show
    @posts = Posts.all
  end


  private

  def post_params
     params.require(:post).permit(:user_id, :text, :image_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :json => @users
  end


  def show
    @user = User.find(params[:id])
  end
end

app/helpers/advertisings_helper.rb
module AdvertisingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name  
    :user
  end

  def resource
  @resource ||= User.new
  end

  def devise_mapping
  @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # :resource_name, :resource, :devise_mapping, :resource_class

 def resource_name
   :user
 end

 def resource
   @resource ||= User.new
 end

 def resource_class
   User
 end

 def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end
end

app/views/home/_form.html.erb
<div class="row ">
  <%= form_for(resource, :as => resource_name,   :html => {:class => "d-flex"}, :url => session_path(resource_name)) do |f| %>
    <div class="col">
      <div><%= f.label :email %><br />
        <%= f.email_field :email, :autofocus => true %></div>
    </div>
    <div class="col">
      <div><%= f.label :password %><br />
        <%= f.password_field :password %></div>
    </div>
    <div class="col align-self-center">
      <div class="main-nav-sign-in-padd"><br />
        <%= f.submit "Sign in" %></div>
    </div>
  <% end %>
</div>

app/views/home/_login_form.html.erb
<div class="row ">
  <%= form_for(resource, :as => resource_name,   :html => {:class => "d-flex"}, :url => session_path(resource_name)) do |f| %>
    <div class="col">
      <div><%= f.label :email %><br />
        <%= f.email_field :email, :autofocus => true %></div>
    </div>
    <div class="col">
      <div><%= f.label :password %><br />
        <%= f.password_field :password %></div>
    </div>
    <div class="col align-self-center">
      <div class="main-nav-sign-in-padd"><br />
        <%= f.submit "Sign in" %></div>
    </div>
  <% end %>
</div>

app/views/home/_signup_form.html.erb
<div class="row ">
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), :html => {:class => "w-100"}) do |f| %>
    <%= devise_error_messages! %>

    <div class="col-12">
      <div class="row">
        <div class="col-12 col-md-6 nopad">
          <div class="field">
            <%= f.text_field :first_name, autofocus: true, placeholder: "First Name", class: "w-100" %>
          </div>
        </div>
        <div class="col-12 col-md-6 nopad">
            <div class="field">
              <%= f.text_field :last_name, autofocus: true, placeholder: "Last Name", class: "w-100" %>
            </div>
        </div>
      </div>
    </div>

    <br />
    <div class="field">
      <%= f.text_field :username, autofocus: true, placeholder: "Username", class: "w-100" %>
    </div>
    <br />
    <div class="field">
      <%= f.email_field :email, autofocus: true, placeholder: "Email", class: "w-100" %>
    </div>
    <br />

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: "w-100" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Password", class: "w-100" %>
    </div>
    <br />
    <div class="field">
      <%= f.text_area :bio, autofocus: true , placeholder: "Bio", class: "w-100" %>
    </div>


    <div class="actions">
      <%= f.submit "Sign up", class: "btn-signup" %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>

  <div class="container-1000">
    <div class="row">
      <div class="d-none col-md-3 d-md-block">
        <div class="feed-left-col-content">
          <ul class="ul-reset">

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-profile-photo-image image align-self-center" style="background-image: url(  <%= Image.where(user_id:   101).first.url %>); ">
                    </div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="/users/<%= current_user.id %>"><%= current_user.first_name %></a></div>
                </div>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-news-feed-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> News Feed</a></div>
                </div>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-messenger-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> Messenger</a></div>
                </div>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-watch-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> Watch</a></div>
                </div>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-marketplace-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> Marketplace</a></div>
                </div>
            </div>

            <div class="interior-contact-row pt-5">
                <p class="sidenav-text-grey">Explore</p>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-events-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> Events</a></div>
                </div>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-groups-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> Groups</a></div>
                </div>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-oculus-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> Oculus</a></div>
                </div>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-pages-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> Pages</a></div>
                </div>
            </div>

            <div class="interior-contact-row">
                <div class="interior-contact-left">
                  <div class="sidenav-profile-photo-size d-inline-block">
                    <div class="sidenav-news-feed-icon image align-self-center"></div>
                  </div>
                </div>
                <div class="interior-contact-right">
                  <div class="align-self-center"><a class="sidenav-username" href="#"> Fundraisers</a></div>
                </div>
            </div>

          </ul>


        </div>
      </div>
      <div class="col-12 col-md-6">
          <% @posts.each do |post| %>
          <div class="users_post">
            <div class="row nopad py-2 pl-3">
              <div class="col-auto p-0">
                <div class="feed_profile_photo_pos">
                  <div class="feed_profile_photo_image image align-self-center" style="background-image: url(  <%= Image.where(user_id: post.user_id).first.url %>); "></div>
                </div>
              </div>
              <div class="col">
                <a href="/users/<%= post.user_id %>/"><%=   User.find(post.user_id).first_name %></a><br>
                <small><%= time_ago_in_words(post.created_at) %> ago &#8226; <%= User.find(post.user_id).location %></small>
              </div>
              <div class="col-auto"><i class="fas fa-ellipsis-h"></i></div>
            </div>
            <br>
            <img src="https://picsum.photos/470/470?image=<%= post.id %>" alt="Users post image">
            <%=   post.text %><br><br><br>
          </div>
          <% end %>
      </div>
      <div class="d-none col-md-3 d-md-block">
        <!-- Right sideBar -->
      </div>
    </div>
  </div>

<% else %>
  <div class="container-1000 py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-md-6">
        <h2>Create a New Account</h2>
        <p>It’s free and always will be.</p>
        <%= render template: './home/_signup_form' %>
      </div>
    </div>
  </div>

<% end %>

app/views/layouts/_form.html.erb
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Latest compiled and minified CSS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <% if user_signed_in? %>
      <nav class="nav-bg">
        <div class="container-1000">
          <div class="row py-2">
            <div class="col-12">
              <ul class="main-nav-links ul-reset d-flex">
                <div class="justify-content-start d-flex align-items-center w-100">
                  <li class="main-nav-main-items">
                    <a href="/" title="home" >
                      <i class="fab fa-facebook-square index-fb-logo"></i>
                    </a>
                  </li>
                  <li class="main-nav-main-items w-100">
                    <form class="form-inline my-2 my-lg-0">
                      <input class="form-control form-control-sm  w80" type="search" placeholder="Search" aria-label="Search">
                    </form>
                  </li>
                </div>

                <div class="justify-content-end d-flex align-items-center w-100">
                  <li class="main-nav-main-items main-nav-left-item d-flex flex-grow-1">
                    <div class="nav-profile-photo-size d-inline-block">
                      <div class="nav-profile-photo-image image align-self-center" style="background-image: url(  <%= Image.where(user_id:   101).first.url %>); ">
                      </div>
                    </div>

                    <div class="align-self-center main-nav-username"><a class="main-nav-username" href="/users/<%= current_user.id %>"><%= current_user.first_name %></a></div>
                  </li>
                  <li class="main-nav-main-items main-nav-left-item"><a href="/">Home</a></li>
                  <li class="main-nav-main-items main-nav-left-item">Create</li>
                  <li class="main-nav-main-items main-nav-left-item nav-icons"><i class="fas fa-user-friends"></i></li>
                  <li class="main-nav-main-items main-nav-left-item nav-icons"><i class="fab fa-facebook-messenger"></i></li>
                  <li class="main-nav-main-items main-nav-left-item nav-icons"><i class="fas fa-bell"></i></li>
                  <li class="main-nav-main-items main-nav-left-item nav-icons"><i class="fas fa-question-circle"></i></li>
                  <li class="main-nav-main-items main-nav-left-item nav-icons">
                    <div class="dropdown d-flex main-nav-main-items">
                      <div class="main-nav-menu-title d-flex align-items-center" id="services-dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-sort-down"></i>
                      </div>
                      <div class="dropdown-menu" >
                        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'main-nav-submenu-link dropdown-item') %>
                      </div>
                    </div>
                  </li>
                </div>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    <% else %>
    <nav class="nav-bg">
      <div class="container-1000">
        <div class="row py-2">
          <div class="col-12">
            <ul class="main-nav-links ul-reset d-flex">
              <div class="justify-content-start d-flex align-items-center w-100">
                <li class="main-nav-main-items">
                  <a href="/" title="home">
                      <div class="main-nav-logo-full-image image"></div>
                  </a>
                </li>
              </div>

              <div class="justify-content-end d-flex align-items-center w-100">
                <li class="main-nav-main-items ">
                    <%= render template: './home/_login_form' %>
                </li>
              </div>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <% end %>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>


  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/show.html.erb
<section>
  <div class="container-1000">
    <div class="row nopad">
      <div class="col-12 usersprofile_header_bg nopad">
        <img src="https://picsum.photos/970/371?image=<%= @user.id %>" alt="Users post image">
      </div>
      <div class="usersprofile_name">
        <p><%= @user.first_name %> <%= @user.last_name %> </p>
      </div>
      <nav class="usersprofile_navbar w-100 py-2">
        <!-- <ul class="ul-reset d-flex justify-content-between"> -->
        <ul class="ul-reset d-flex usersprofile_nav_items-group">
          <li class="usersprofile_nav_items"><a href="">Timeline</a></li>
          <li class="usersprofile_nav_items"><a href="">About</a></li>
          <li class="usersprofile_nav_items"><a href="">Friends</a></li>
          <li class="usersprofile_nav_items"><a href="">Photos</a></li>
          <li class="usersprofile_nav_items"><a href="">Archive</a></li>
          <li class="usersprofile_nav_items"><a href="">More</a></li>
        </ul>
      </nav>
      <div class="usersprofile_profile_photo">
          <div class="usersprofile_profile_photo_pos">
            <div class="usersprofile_profile_photo_image image align-self-center" style="background-image: url(  <%= Image.where(user_id: @user.id).first.url %>); ">
            </div>
        </div>
      </div>
    </div>
  </div>
</section>